import "./globals.css";
import { Poppins} from "next/font/google";
import Nav from "@/Components/Nav";
import { Metadata } from "next";
import NeonCircles from "@/Components/NeonCircles";
import { ThemeProvider } from "@/Components/Providers/theme-provider";
import { SWRProvider } from "@/Components/Providers/Swr-provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "700", "900", "800"],
});

export const metadata: Metadata = {
  title: "Cryptos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      <body
        className={`min-h-screen bg-background font-sans antialiased ${poppins.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SWRProvider>
            <Nav />
            <NeonCircles />
            <main className={"container duration-500 ease-in-out"}>
              {children}
            </main>
          </SWRProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
